// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnt5cViOsLFpG7SWRSjZzNVhBkAqGqiP4',
    appId: '1:911794298081:web:0d35455a05d75ec1516ba0',
    messagingSenderId: '911794298081',
    projectId: 'e-alert-7510c',
    authDomain: 'e-alert-7510c.firebaseapp.com',
    storageBucket: 'e-alert-7510c.appspot.com',
    measurementId: 'G-7HC62490JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDunLwb-D-JNyi2-ci05E78hwTCxidqO9E',
    appId: '1:911794298081:android:b18f66786c955554516ba0',
    messagingSenderId: '911794298081',
    projectId: 'e-alert-7510c',
    storageBucket: 'e-alert-7510c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvfgamms-uCU3IbNTLjRbSiwn1xgLH5zc',
    appId: '1:911794298081:ios:d906f6159a9cbbae516ba0',
    messagingSenderId: '911794298081',
    projectId: 'e-alert-7510c',
    storageBucket: 'e-alert-7510c.appspot.com',
    iosBundleId: 'com.example.try1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvfgamms-uCU3IbNTLjRbSiwn1xgLH5zc',
    appId: '1:911794298081:ios:f0490a9f43b5be7c516ba0',
    messagingSenderId: '911794298081',
    projectId: 'e-alert-7510c',
    storageBucket: 'e-alert-7510c.appspot.com',
    iosBundleId: 'com.example.try1.RunnerTests',
  );
}
